# This workflow runs on pushes to the main branch.
name: CI Pipeline

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Triggers on push events to the main branch
  pull_request:
    branches: [ "main" ] # Also triggers on pull requests to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Add the strategy and matrix here
    strategy:
      matrix:
        # Define the matrix of Python versions to test against
        python-version: ['3.11', '3.12', '3.9', '3.10']

    steps:
      - name: Print Hello Message
        run: echo "Hello, CI with GitHub Actions!"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          # Use the python-version from the matrix
          python-version: ${{ matrix.python-version }}

      - name: Run Python tests
        run: python -m unittest test_main.py
